services:
  db:
    image: postgres:latest
    container_name: gps_postgres
    restart: always
    environment:
      POSTGRES_USER: azamba
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: gps_tracker
    ports:
      - "5434:5432"  # Corrigido aqui!
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gps_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: gps_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gps.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - gps_network

volumes:
  pgdata:
networks:
  gps_network:
