version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: gps_postgres
    restart: always
    environment:
      POSTGRES_USER: gps_user
      POSTGRES_PASSWORD: gps_password
      POSTGRES_DB: gps_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gps_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: gps_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gps.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - gps_network

  backend:
    build: ./backend
    container_name: gps_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://gps_user:gps_password@db:5432/gps_database
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - gps_network

volumes:
  pgdata:

networks:
  gps_network:
